server:
  forward-headers-strategy: framework
spring:
  webflux:
    base-path: /ssp/api-css-budget
  application:
    name: css-budget
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: UTC
    serialization:
      write_date_timestamps_as_nanoseconds: false
      WRITE_DATES_AS_TIMESTAMPS: false
      fail_on_empty_beans: false
    deserialization:
      fail_on_unknown_properties: false
  r2dbc:
    url: 'r2dbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: 'postgres'
    properties:
      schema: cpm_css
    pool:
      enabled: true
      initial-size: 10
      max-size: 50
      max-idle-time: 30m
      validation-query: SELECT 1
  liquibase:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    change-log: classpath:db/migration/changelog.xml
    default-schema: ${spring.r2dbc.properties.schema}
    enabled: true
  mustache:
    check-template-location: false

springdoc:
  swagger-ui:
    doc-expansion: none
    tags-sorter: alpha
    operations-sorter: method